version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "NPM Prod"
      prefix-development: "NPM Dev"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "PIP Prod"
      prefix-development: "PIP Dev"
      include: "scope"
